name: design-flow-payload-action
on: repository_dispatch
jobs:
  design:
    name: Tokens
    if: github.event.action == 'update-tokens'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo '${{ github.event.client_payload.tokens }}' > design/tokens/properties/${{ github.event.client_payload.tokenFileName }}
      - run: npm run design-tokens

